### ISSUE TITLE
[Bug] [restful api ] After enabling Basic authentication, downloading the log file results in a JSON deserialization exception.

### ISSUE THREAD

**Issue by yuxiaoxu12138** [apache/seatunnel#10027]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

After enabling Basic authentication, an exception occurs when calling the "Get Logs from All Nodes" API. When I disable Basic authentication, it works normally again.

### SeaTunnel Version

seatunnel 2.3.11

### SeaTunnel Config

```conf
seatunnel:
  engine:
    classloader-cache-mode: true
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///tmp/ # Ensure that the directory has written permission
    telemetry:
      metric:
        enabled: false
      logs:
        scheduled-deletion-enable: true
    http:
      enable-http: true
      port: 8080
      enable-dynamic-port: false
      # Uncomment the following lines to enable basic authentication for web UI
      enable-basic-auth: true
      basic-auth-username: admin
      basic-auth-password: admin
```

### Running Command

```shell
curl --location --request GET 'http://192.168.10.130:8080/logs/1038081781514895361?format=json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Accept: */*' \
--header 'Host: 192.168.10.130:8080' \
--header 'Connection: keep-alive'
```

### Error Exception

```log
2025-11-04 21:35:00,939 DEBUG [o.a.s.e.s.r.s.LogService      ] [qtp1036606347-111] - Request: http://192.168.10.130:8080 , Result: null
2025-11-04 21:35:01,071 ERROR [.s.r.f.ExceptionHandlingFilter] [qtp1036606347-111] - Error occurred while processing request
java.lang.RuntimeException: Json deserialization exception.
	at org.apache.seatunnel.common.utils.JsonUtils.parseArray(JsonUtils.java:279) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.engine.server.rest.service.LogService.lambda$allLogNameList$1(LogService.java:76) ~[seatunnel-starter.jar:2.3.11]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_311]
	at org.apache.seatunnel.engine.server.rest.service.LogService.allLogNameList(LogService.java:70) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.engine.server.rest.service.LogService.allNodeLogFormatJson(LogService.java:97) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.engine.server.rest.servlet.AllNodeLogServlet.doGet(AllNodeLogServlet.java:69) ~[seatunnel-starter.jar:2.3.11]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.11]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.engine.server.rest.filter.BasicAuthFilter.doFilter(BasicAuthFilter.java:90) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.engine.server.rest.filter.ExceptionHandlingFilter.doFilter(ExceptionHandlingFilter.java:50) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.Server.handle(Server.java:516) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[seatunnel-starter.jar:2.3.11]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.IllegalArgumentException: argument "content" is null
	at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4829) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3074) ~[seatunnel-starter.jar:2.3.11]
	at org.apache.seatunnel.common.utils.JsonUtils.parseArray(JsonUtils.java:277) ~[seatunnel-starter.jar:2.3.11]
	... 38 more
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

java

### Screenshots

<img width="1390" height="1113" alt="Image" src="https://github.com/user-attachments/assets/be3e98a9-6dbc-47f6-ad80-4edcdef5f4be" />

This method does not handle authentication, causing the request to the "http://192.168.10.130:8080/get-all-log-name" endpoint to return an HTTP status 401.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dybyte** [comment]
Hi @yuxiaoxu12138 ,
This issue has been resolved in #9977 .

**Comment by yuxiaoxu12138** [comment]
> 您好，此问题已在 [#9977](https://github.com/apache/seatunnel/pull/9977) 中解决。

In #9977, only the result was handled, but the issue itself wasn't resolved. The problem arises because Basic authentication credentials were not included when calling "sendGet".

**Comment by dybyte** [comment]
> In https://github.com/apache/seatunnel/pull/9977, only the result was handled, but the issue itself wasn't resolved. The problem arises because Basic authentication credentials were not included when calling "sendGet".


Thanks for the clarification. Please refer to #9968 .

**Comment by yuxiaoxu12138** [comment]
> > 在 [#9977](https://github.com/apache/seatunnel/pull/9977) 中，只处理了结果，但问题本身没有解决。出现此问题的原因是，在调用“sendGet”时未包含基本身份验证凭据。
> 
> 感谢您的澄清。请参阅 [#9968](https://github.com/apache/seatunnel/pull/9968) 。
Thanks for your feedback—this is indeed as described in "#9968." We're very much looking forward to it!

**Comment by Level1Accelerator** [comment]
+1

**Comment by dybyte** [comment]
We can close this issue via #9968. @zhangshenghang
