### ISSUE TITLE
[Bug] [CheckPoint] increase checkpoint timeout

### ISSUE THREAD

**Issue by EngonVHKxZ** [apache/seatunnel#5722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I use batch mode to synchronize data, I always prompt for checkpoint timeout

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: hdfs://hadoop-001:8020


env {
    job.mode="BATCH",
    execution.parallelism=5
},
source {
    Jdbc {
        url="jdbc:oracle:thin:@//IP:PORT/ServiceName",
        driver="oracle.jdbc.OracleDriver",
        user="username",
        password="pwd",
        query="select CLASS_CODE,SPELL_CODE,MODIFY_OPERATOR,WBZX_CODE,OPERATION_GRADE,CREATE_OPERATOR,NAME,SEX_LIMIT,CODE,AGE_LIMIT_L,SOURCE,VERSION,AGE_LIMIT_H,ID,CREATE_TIME,REMARK,SORT_NO,VALID_FLAG,MODIFY_TIME from username.KOHD order by ID",
        fetch_size=10000
    }
},
transform  {},
sink {
    Jdbc {
        url="jdbc:oracle:thin:@//IP:PORT/ServiceName",
        driver="oracle.jdbc.OracleDriver",
        user="username",
        password="pwd",
        generate_sink_sql=true,
        database="ORCL",
        table="username.KOHD2",
        xa_data_source_class_name="oracle.jdbc.xa.client.OracleXADataSource",
        is_exactly_once="true",
        auto_commit="true"
    }
}
```

### Running Command

```shell
seatunnel.sh -c oracle2oracle.config
```

### Error Exception

```log
2023-10-26 15:27:04,899 INFO  org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - wait checkpoint completed: 7
2023-10-26 15:27:04,903 INFO  org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - timeout checkpoint: 769824035470049281/1/1, CHECKPOINT_TYPE
2023-10-26 15:27:04,904 INFO  org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - start clean pending checkpoint cause Checkpoint expired before completing. Please increase checkpoint timeout in the seatunnel.yaml
2023-10-26 15:27:04,904 ERROR org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - trigger checkpoint failed
org.apache.seatunnel.engine.server.checkpoint.CheckpointException: Checkpoint expired before completing. Please increase checkpoint timeout in the seatunnel.yaml
        at org.apache.seatunnel.engine.server.checkpoint.PendingCheckpoint.abortCheckpoint(PendingCheckpoint.java:172) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.lambda$cleanPendingCheckpoint$19(CheckpointCoordinator.java:645) ~[seatunnel-starter.jar:2.3.3]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4770) ~[?:?]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.cleanPendingCheckpoint(CheckpointCoordinator.java:643) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.handleCoordinatorError(CheckpointCoordinator.java:261) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.lambda$null$9(CheckpointCoordinator.java:532) ~[seatunnel-starter.jar:2.3.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2023-10-26 15:27:04,904 ERROR org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - trigger checkpoint failed
org.apache.seatunnel.engine.server.checkpoint.CheckpointException: Checkpoint expired before completing. Please increase checkpoint timeout in the seatunnel.yaml
        at org.apache.seatunnel.engine.server.checkpoint.PendingCheckpoint.abortCheckpoint(PendingCheckpoint.java:172) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.lambda$cleanPendingCheckpoint$19(CheckpointCoordinator.java:645) ~[seatunnel-starter.jar:2.3.3]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4770) ~[?:?]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.cleanPendingCheckpoint(CheckpointCoordinator.java:643) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.handleCoordinatorError(CheckpointCoordinator.java:261) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.lambda$null$9(CheckpointCoordinator.java:532) ~[seatunnel-starter.jar:2.3.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2023-10-26 15:27:04,904 ERROR org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - trigger checkpoint failed
org.apache.seatunnel.engine.server.checkpoint.CheckpointException: Checkpoint expired before completing. Please increase checkpoint timeout in the seatunnel.yaml
        at org.apache.seatunnel.engine.server.checkpoint.PendingCheckpoint.abortCheckpoint(PendingCheckpoint.java:172) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.lambda$cleanPendingCheckpoint$19(CheckpointCoordinator.java:645) ~[seatunnel-starter.jar:2.3.3]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4770) ~[?:?]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.cleanPendingCheckpoint(CheckpointCoordinator.java:643) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.handleCoordinatorError(CheckpointCoordinator.java:261) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.lambda$null$9(CheckpointCoordinator.java:532) ~[seatunnel-starter.jar:2.3.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Java or Scala Version

JDK11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lukeyan2023** [comment]
This should not be a bug, just increase the checkpoint timeout according to the log prompts. I also encountered this issue, and after increasing the timeout, the problem was resolved

**Comment by EngonVHKxZ** [comment]
> This should not be a bug, just increase the checkpoint timeout according to the log prompts. I also encountered this issue, and after increasing the timeout, the problem was resolved

i tried, but this solution is not work 4 me :(

**Comment by mengyueyue** [comment]
i met this in 2.3.4 version , like:
`Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.engine.server.checkpoint.CheckpointException: Checkpoint expired before completing. Please increase checkpoint timeout in the seatunnel.yaml or jobConfig env.`
and i tried increasing checkpoint.timeout and checkpoint.interval in jobConfig env, it worked!

**Comment by EngonVHKxZ** [comment]
Version 2.3.4 has not been released yet, and the config may change at any time. The company only allows stable versions, so...... I have to wait for the next stable version to be released or fixed with patches

**Comment by EngonVHKxZ** [comment]
> i met this in 2.3.4 version , like: `Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.engine.server.checkpoint.CheckpointException: Checkpoint expired before completing. Please increase checkpoint timeout in the seatunnel.yaml or jobConfig env.` and i tried increasing checkpoint.timeout and checkpoint.interval in jobConfig env, it worked!

Version 2.3.4 has not been released yet, and the config may change at any time. The company only allows stable versions, so...... I have to wait for the next stable version to be released or fixed with patches

**Comment by codeDing18** [comment]
> i met this in 2.3.4 version , like: `Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.engine.server.checkpoint.CheckpointException: Checkpoint expired before completing. Please increase checkpoint timeout in the seatunnel.yaml or jobConfig env.` and i tried increasing checkpoint.timeout and checkpoint.interval in jobConfig env, it worked!

hi @mengyueyue.How much data do you synchronize? I have a table whose size is 7.4g and timeout has been increased. But I still get this error.

**Comment by mengyueyue** [comment]
> > i met this in 2.3.4 version , like: `Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.engine.server.checkpoint.CheckpointException: Checkpoint expired before completing. Please increase checkpoint timeout in the seatunnel.yaml or jobConfig env.` and i tried increasing checkpoint.timeout and checkpoint.interval in jobConfig env, it worked!
> 
> hi @mengyueyue.How much data do you synchronize? I have a table whose size is 7.4g and timeout has been increased. But I still get this error.

my data size is 4.7g  and i set int max value for them

**Comment by codeDing18** [comment]
> > > i met this in 2.3.4 version , like: `Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.engine.server.checkpoint.CheckpointException: Checkpoint expired before completing. Please increase checkpoint timeout in the seatunnel.yaml or jobConfig env.` and i tried increasing checkpoint.timeout and checkpoint.interval in jobConfig env, it worked!
> > 
> > 
> > hi @mengyueyue.How much data do you synchronize? I have a table whose size is 7.4g and timeout has been increased. But I still get this error.
> 
> my data size is 4.7g and i set int max value for them

thx for reply

**Comment by cyc0601** [comment]
i also encountered same problem.  finally i found the reason is table missing primary key.

**Comment by DanielLeens** [comment]
Thanks for following up.

If the timeout was ultimately caused by a table without a primary key, that points more to a source / table-contract problem than to a generic checkpoint-timeout bug. In that case, the checkpoint timeout was likely the symptom rather than the root cause.

Since this thread is based on an old SeaTunnel version and was already auto-closed long ago, let's keep it closed for now.

If you still see the same problem on a current release, please open a new issue with:
1. the exact SeaTunnel version
2. the connector type and job mode
3. whether the source table has a primary key
4. the complete stack trace around the timeout

That will help us determine whether there is still a runtime bug beyond the table-definition constraint.
